import type { Recipe } from "./types"

export const sampleRecipes: Recipe[] = [
  {
    id: "rec1",
    name: "Velvet Tomato Serenade",
    ingredients: [
      { name: "ripe tomatoes", emoji: "🍅" },
      { name: "fresh basil", emoji: "🌿" },
      { name: "garlic cloves", emoji: "🧄" },
      { name: "olive oil", emoji: "🫒" },
      { name: "balsamic vinegar", emoji: "🍶" },
    ],
    cookingTime: 25,
    difficulty: "Easy",
    steps: [
      "Blanch tomatoes in boiling water for 30 seconds, then transfer to ice water.",
      "Peel tomatoes and cut into quarters, removing seeds.",
      "In a food processor, combine tomatoes, torn basil leaves, and minced garlic.",
      "Pulse until desired consistency is reached.",
      "Slowly drizzle in olive oil while pulsing.",
      "Season with salt and pepper to taste.",
      "Finish with a splash of balsamic vinegar before serving.",
    ],
    servingSuggestion:
      "Serve chilled in crystal glasses with a basil leaf garnish and grilled sourdough crostini on the side.",
  },
  {
    id: "rec2",
    name: "Midnight Mushroom Rhapsody",
    ingredients: [
      { name: "wild mushrooms", emoji: "🍄" },
      { name: "fresh thyme", emoji: "🌿" },
      { name: "shallots", emoji: "🧅" },
      { name: "heavy cream", emoji: "🥛" },
      { name: "truffle oil", emoji: "🫒" },
    ],
    cookingTime: 35,
    difficulty: "Medium",
    steps: [
      "Clean mushrooms with a damp cloth and slice them thinly.",
      "Finely dice shallots and sauté in butter until translucent.",
      "Add mushrooms and cook until they release their moisture and begin to brown.",
      "Deglaze the pan with a splash of white wine.",
      "Add fresh thyme leaves and heavy cream, reducing until slightly thickened.",
      "Season with salt and freshly ground black pepper.",
      "Finish with a few drops of truffle oil just before serving.",
    ],
    servingSuggestion: "Serve in a shallow black ceramic bowl with a swirl of truffle oil and a sprig of fresh thyme.",
  },
  {
    id: "rec3",
    name: "Golden Saffron Embrace",
    ingredients: [
      { name: "arborio rice", emoji: "🍚" },
      { name: "saffron threads", emoji: "🌱" },
      { name: "white wine", emoji: "🍷" },
      { name: "parmesan cheese", emoji: "🧀" },
      { name: "vegetable broth", emoji: "🥣" },
    ],
    cookingTime: 40,
    difficulty: "Medium",
    steps: [
      "Toast arborio rice in butter until translucent around the edges.",
      "Add white wine and stir until absorbed.",
      "Steep saffron threads in warm broth for 5 minutes.",
      "Gradually add saffron-infused broth to rice, stirring constantly.",
      "Continue adding broth and stirring until rice is creamy and al dente.",
      "Remove from heat and fold in grated parmesan cheese.",
      "Let rest for 2 minutes before serving.",
    ],
    servingSuggestion:
      "Serve on a warmed plate, shaped into a perfect circle, with edible gold leaf and a light dusting of additional saffron.",
  },
  {
    id: "rec4",
    name: "Aromatic Citrus Symphony",
    ingredients: [
      { name: "salmon fillet", emoji: "🐟" },
      { name: "orange", emoji: "🍊" },
      { name: "lemon", emoji: "🍋" },
      { name: "fresh dill", emoji: "🌿" },
      { name: "honey", emoji: "🍯" },
    ],
    cookingTime: 22,
    difficulty: "Easy",
    steps: [
      "Zest and juice the orange and lemon.",
      "Whisk together citrus juices, zest, honey, and chopped dill to create a marinade.",
      "Place salmon in the marinade for 15 minutes.",
      "Preheat oven to 375°F (190°C).",
      "Remove salmon from marinade and place on a baking sheet.",
      "Bake for 12-15 minutes until salmon flakes easily with a fork.",
      "While salmon bakes, reduce remaining marinade in a small saucepan to create a glaze.",
    ],
    servingSuggestion:
      "Serve on a bed of wilted spinach with the citrus glaze drizzled over the top and thin slices of citrus arranged around the plate.",
  },
  {
    id: "rec5",
    name: "Rustic Eggplant Ballad",
    ingredients: [
      { name: "eggplant", emoji: "🍆" },
      { name: "tomatoes", emoji: "🍅" },
      { name: "bell peppers", emoji: "🫑" },
      { name: "onions", emoji: "🧅" },
      { name: "garlic", emoji: "🧄" },
    ],
    cookingTime: 45,
    difficulty: "Medium",
    steps: [
      "Dice eggplant, tomatoes, bell peppers, and onions into similar-sized pieces.",
      "Mince garlic and sauté in olive oil until fragrant.",
      "Add onions and cook until translucent.",
      "Add bell peppers and cook for 5 minutes.",
      "Add eggplant and cook until it begins to soften.",
      "Add tomatoes, herbs, and seasonings.",
      "Simmer uncovered for 30 minutes, stirring occasionally.",
    ],
    servingSuggestion:
      "Serve in a rustic earthenware bowl with a drizzle of extra virgin olive oil and a sprinkle of fresh herbs.",
  },
  {
    id: "rec6",
    name: "Dreamy Avocado Cascade",
    ingredients: [
      { name: "ripe avocados", emoji: "🥑" },
      { name: "lime", emoji: "🍋" },
      { name: "cilantro", emoji: "🌿" },
      { name: "red onion", emoji: "🧅" },
      { name: "jalapeño", emoji: "🌶️" },
    ],
    cookingTime: 15,
    difficulty: "Easy",
    steps: [
      "Halve and pit the avocados, then scoop the flesh into a bowl.",
      "Mash avocados with a fork to desired consistency.",
      "Finely dice red onion and jalapeño.",
      "Chop cilantro leaves.",
      "Add diced ingredients to the mashed avocado.",
      "Squeeze fresh lime juice over the mixture and stir to combine.",
      "Season with salt and freshly ground black pepper to taste.",
    ],
    servingSuggestion:
      "Serve in a molcajete with blue corn tortilla chips arranged in a circular pattern around the edge.",
  },
]
